Add support for custom newsletter fields
vtex-apps/store-newsletter pull request #5
Opened 2020-12-17 19:02 UTC by victorhmp

#### What problem is this solving?

#### How to test it?

[Workspace](Link goes here!)

#### Screenshots or example usage:

#### Describe alternatives you've considered, if any.

#### Related to / Depends on

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](put .gif link here - can be found under "advanced" on giphy)

2020-12-18 18:49 UTC, victorhmp commented
Still working on the documentation :)

2020-12-22 17:48 UTC, klzns requested changes

2020-12-22 17:48 UTC, klzns commented on react/FormHiddenField.tsx
> +    return resolvedCustomField
⛏️  I kind of prefer code without `else`. You decide which is best though

```suggestion
    const resolvedCustomField: ResolvedCustomField = {
      name: customField.fieldName,
      value: null,
    }

    if (customField?.value) {
      resolvedCustomField.value = customField.value
    }

    if (customField?.dynamicValue === 'bindingUrl') {
      resolvedCustomField.value = runtime.binding?.canonicalBaseAddress ?? null
    } 

    if (customField?.dynamicValue === 'bindingId') {
      resolvedCustomField.value = runtime.binding?.id ?? null
    }

    return resolvedCustomField
```

2020-12-22 17:48 UTC, klzns commented on react/NewsletterContext.tsx
> +    case 'SET_CUSTOM_VALUES': {
VTEX IO apps only export the `export default` of entrypoints. I think we have to change this file

2020-12-29 16:17 UTC, guerreirobeatriz requested changes

2020-12-29 16:17 UTC, guerreirobeatriz commented on docs/README.md
> +
```suggestion
### `newsletter-hidden-field` props

| Prop name | Type | Description | Default value |
| :---------: | :----: | :----------: | :-------------: |
| `customFields` | `object` | Enables you to specify a certain custom user field that should always be sent along with a user's newsletter subscription. | `undefined` |

- **`customFields` object:**

| Prop name | Type | Description | Default value |
| :---------: | :----: | :----------: | :-------------: |
| `fieldName` | `string` | Text string that should match the field's name in your Master Data user schema. | `undefined` | 
|  `dynamicValue` | `enum` | Possible values are: `bindingId` and `bindingUrl`. Both of these values will be calculated by the `newsletter-hidden-field` block before sending the newsletter subscription data. | `undefined` |
| ` value` | `string` | Static value sent to users when they submit the newsletter form. *Caution*: the value will always be the same. | `undefined` | 

:warning: *The `value` and `dynamicValue` props are conflicting and must not be declared together.*

```

2020-12-29 16:17 UTC, guerreirobeatriz commented on docs/README.md
> +
I don't think I fully understood the idea. The descriptions are still confused to me, I think we can clarify the modus operandi behind this object!

2020-12-29 16:17 UTC, guerreirobeatriz commented on docs/README.md
> +
The new block is missing in the block list (at the top of the documentation)

2021-01-12 20:18 UTC, klzns approved these changes

2021-01-13 21:41 UTC, icazevedo approved these changes

2021-02-03 15:47 UTC, guerreirobeatriz requested changes

2021-02-03 15:47 UTC, guerreirobeatriz commented on docs/README.md
> +| `newsletter-hidden-field`          | Doesn't render anything, but enables custom fields to be sent when a user subscribes to the store's newsletter.      |
```suggestion
| `newsletter-hidden-field`          | Doesn't render anything, but enables hidden fields on the form to fetch custom data and save them in the store's Master Data whenever a user subscribes to the newsletter. |
```

2021-02-03 15:47 UTC, guerreirobeatriz commented on docs/README.md
> +| `dynamicFields`     | `Array<'bindingUrl' | 'bindingId'>` | An array of strings that represent dynamic fields that will be sent to the `subscribeNewsletter` mutation call performed when a user subs
```suggestion
### `newsletter-hidden-field` props

| Prop name | Type     | Description                 | Default value |
| --------- | -------- | --------------------------- | ------------- |
| `dynamicFields` | `[enum]` | Desired hidden fields responsible for saving the user's custom data on [Master Data](https://help.vtex.com/en/tutorial/what-is-master-data--4otjBnR27u4WUIciQsmkAw) once the newsletter form is submitted. Notice that the name of the fields must be written in an array and represent which user data they save. Possible values are: `bindingUrl` and `bindingId`. *Caution*: To properly save the data, you must also [create the desired filters](https://help.vtex.com/en/tutorial/how-can-i-create-a-field-in-master-data--frequentlyAskedQuestions_1829) in the Master Data's `Client` entity.  | `undefined` |
```

2021-02-03 19:42 UTC, merged